# Generated by Django 4.2.29 on 2026-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_theme_color',
            field=models.CharField(default='#1e1e1e', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark'), ('black_white', 'Black White'), ('custom', 'Custom')], default='dark', max_length=20),
        ),
    ]
