# Generated by Django 4.2.29 on 2026-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donorprofile_city_donorprofile_is_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
