# Generated by Django 4.2.29 on 2026-05-09 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organrecord_blockchain_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blockchain_address',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='blockchain_wallet_address',
            field=models.CharField(blank=True, help_text='Ethereum Address from Ganache', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
