# Generated by Django 4.2.29 on 2026-05-09 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_hospitalprofile_blockchain_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospitalprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
