# Generated by Django 5.2.8 on 2026-06-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_recipient_donorprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrecord',
            name='blockchain_id',
            field=models.IntegerField(blank=True, help_text='ID from Blockchain', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organrecord',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_organs', to='core.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='organrecord',
            name='status',
            field=models.CharField(choices=[('Pledged', 'Pledged'), ('Available', 'Available'), ('Matched', 'Matched'), ('Transplanted', 'Transplanted')], default='Available', max_length=20),
        ),
    ]
