# Generated by Django 5.2.8 on 2026-06-14 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_organrecord_blockchain_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='assigned_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_donors', to='core.hospitalprofile'),
        ),
    ]
