# Generated by Django 5.2.8 on 2026-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_donorprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='pledged_organ',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
