# Generated by Django 5.2.8 on 2026-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_donorprofile_pledged_organ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark'), ('black_white', 'Black White'), ('custom', 'Custom')], default='white', max_length=20),
        ),
    ]
