# Generated by Django 5.2.8 on 2026-06-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='blockchain_hash',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='user',
        ),
    ]
