# Generated by Django 5.2.8 on 2026-06-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_donorprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transplant',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_organs', to='core.recipient'),
        ),
    ]
