# Generated by Django 4.2.29 on 2026-06-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_transplant_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Verification', 'Pending Verification'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='organrecord',
            name='status',
            field=models.CharField(choices=[('Pledged', 'Pledged'), ('Pending Verification', 'Pending Verification'), ('Available', 'Available'), ('Matched', 'Matched'), ('Transplanted', 'Transplanted')], default='Pending Verification', max_length=30),
        ),
    ]
