# Generated by Django 5.2.8 on 2026-06-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_donorprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='blockchain_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('On Blockchain', 'On Blockchain'), ('Matched', 'Matched'), ('Approved', 'Approved'), ('Organ Transported', 'Organ Transported'), ('Transplant Completed', 'Transplant Completed'), ('Transplanted', 'Transplanted')], default='Requested', max_length=30),
        ),
    ]
