# Generated by Django 4.2.29 on 2026-06-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_recipient_blockchain_id_recipient_blockchain_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organrecord',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Available', 'Available'), ('Rejected', 'Rejected'), ('Matched', 'Matched'), ('Transplanted', 'Transplanted')], default='Registered', max_length=30),
        ),
        migrations.CreateModel(
            name='OrganStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organ_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.organrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
