# Generated by Django 4.2.29 on 2026-06-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organrecord_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrecord',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Organ Suitable', 'Organ Suitable'), ('Organ Rejected', 'Organ Rejected'), ('Submitted to Admin', 'Submitted to Admin'), ('Available', 'Available'), ('Rejected', 'Rejected'), ('Matched', 'Matched'), ('Transplanted', 'Transplanted'), ('Case Closed', 'Case Closed')], default='Registered', max_length=30),
        ),
    ]
