# Generated by Django 4.2.29 on 2026-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_organrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Testing', 'Testing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
