# Generated by Django 4.2.29 on 2026-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_donorprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrecord',
            name='medical_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Testing', 'Under Testing'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Organ Failure', 'Organ Failure'), ('Rejected', 'Rejected'), ('Deceased', 'Deceased')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='organrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Testing', 'Under Testing'), ('Approved', 'Approved'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Organ Failure', 'Organ Failure'), ('Rejected', 'Rejected'), ('Deceased', 'Deceased'), ('Admin Approved', 'Admin Approved'), ('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Organ Suitable', 'Organ Suitable'), ('Organ Rejected', 'Organ Rejected'), ('Submitted to Admin', 'Submitted to Admin'), ('Available', 'Available'), ('Rejected', 'Rejected'), ('Matched', 'Matched'), ('Transplanted', 'Transplanted'), ('Case Closed', 'Case Closed')], default='Pending', max_length=30),
        ),
    ]
