# Generated by Django 4.2.29 on 2026-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_organrecord_medical_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Testing', 'Under Testing'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Organ Failure', 'Organ Failure'), ('Rejected', 'Rejected'), ('Deceased', 'Deceased'), ('Death but Eligible Transplant', 'Death but Eligible Transplant'), ('Death but Ineligible Transplant', 'Death but Ineligible Transplant')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='organrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Testing', 'Under Testing'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Organ Failure', 'Organ Failure'), ('Rejected', 'Rejected'), ('Deceased', 'Deceased'), ('Death but Eligible Transplant', 'Death but Eligible Transplant'), ('Death but Ineligible Transplant', 'Death but Ineligible Transplant'), ('Admin Approved', 'Admin Approved'), ('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Organ Suitable', 'Organ Suitable'), ('Organ Rejected', 'Organ Rejected'), ('Submitted to Admin', 'Submitted to Admin'), ('Available', 'Available'), ('Matched', 'Matched'), ('Transplanted', 'Transplanted'), ('Case Closed', 'Case Closed'), ('Waiting For Blockchain Approval', 'Waiting For Blockchain Approval'), ('Blockchain Verified', 'Blockchain Verified')], default='Pending', max_length=50),
        ),
    ]
